title: Fernando Borretti
description: Personal website
baseurl: ""
url: "http://borretti.me/"


markdown: kramdown

kramdown:
  parse_block_html: true

highlighter: rouge

sass:
    style: :compressed

# Default layout
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

permalink: /article/:title

# Custom variables

post_images: /assets/img/posts

# Post resources

post_resources:
  css: []
  js: []

# Portfolio variables

links:
  - service: github
    url: https://github.com/eudoxia0
  - service: linkedin
    url: https://www.linkedin.com/pub/fernando-borretti/74/b74/827
