title: Fernando Borretti
description: Personal website
baseurl: ""
url: "http://borretti.me/"


markdown: kramdown

kramdown:
  parse_block_html: true

highlighter: none
kramdown:
   syntax_highlighter_opts:
      disable : true

sass:
    style: :compressed

# Default layout
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

permalink: /article/:title

# Custom variables

post_images: /assets/img/posts

# Post resources

post_resources:
  css:
    - /assets/css/syntax-highlighting.css
    - //maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css
  js:
    - //ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js
    - /assets/js/highlight.min.js
    - //cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - /assets/js/scripts.js

# Portfolio variables

links:
  - service: github
    url: https://github.com/eudoxia0
  - service: linkedin
    url: https://www.linkedin.com/pub/fernando-borretti/74/b74/827
