title: Fernando Borretti
description: Personal website
baseurl: ""
url: "http://yourdomain.com"
markdown: kramdown
sass:
    style: :compressed

js:
  - "https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.3/highlight.min.js"
  - "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
